theme: jekyll-theme-slate
title: Pages Playground
description: playground for trying out github pages
remote_theme: just-the-docs/just-the-docs
search_enabled: true
# Maximum amount of previews per search result
# Default: 3
search.previews: 3

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 10

